### ISSUE TITLE
Failed to execute 'le on' management command.

### ISSUE THREAD

**Issue by alphaomicron** [evilsocket/bleah#13]
Although I tried to clean install for second time I do get the same issue.Any thoughts? 
![screenshot](https://user-images.githubusercontent.com/28708988/31052664-ff21c6ae-a693-11e7-8d10-515837f9300c.jpg)

**Comment by evilsocket** [comment]
Did you verify that your BT device is BLE compatible?

    sudo hcitool lescan

**Comment by y0d4a** [comment]
same issue here, but scanning is working...

sudo hcitool lescan
LE Scan ...
F8:3F:51:23:FB:xx (unknown)
00:1E:C0:2F:DE:XX BLE_IMA
00:1E:C0:2F:DE:XX (unknown)
72:8C:2F:40:9B:XX (unknown)
72:8C:2F:40:9B:XX (unknown)
38:01:95:DF:F5:XX (unknown)

any suggestion?

**Comment by ashish-bhangale** [comment]
Receiving the same error any solution?

**Comment by evilsocket** [comment]
This is a bluepy bug, nothing i can do (other than catching the exception) from my side.

**Comment by emdete** [comment]
bluepy comes with a native binary called bluepy-helper which must be allowed to access bt. so either run bleah as root (because the binary is started from bleah) or issue a

```
setcap 'cap_net_raw,cap_net_admin+eip' .../site-packages/bluepy/bluepy-helper
```

(figure out, where that binary is installed on your system) which fixed the issue for me.

**Comment by y0d4a** [comment]
working with this, thank you!
