### ISSUE TITLE
Output to non-Curses format

### ISSUE THREAD

**Issue by tautology0** [evilsocket/bleah#15]
The main reason why I want to use bleah was to have an easy way of dumping characteristics for reports. I'd used some custom scripts with nobel to do this before; but the utter mankiness of nodejs made this way harder than anything as simple as BLE ought to be. 

The bleah table is everything I need; but the curses table is a bit inflexible. So, can we have an -o option to write the enumeration table to a generic file format (e.g. a TSV file)?

**Comment by evilsocket** [comment]
that's a very smart feature request, i'll make sure to implement it as soon as i'll have some time for the project :+1: thanks for the feedback

**Comment by haxorthematrix** [comment]
I was coming to specifically request the same, and found that it was here already.  I'd love to try to do it, but not enough hours exist in my day  :-(

I second this request

**Comment by tautology0** [comment]
I did have a go at this a while back, but I needed a global variable for it to work; so I didn't mess with it any more.

**Comment by elkentaro** [comment]
My fork version doesl log the scan results to a file.

**Comment by Thorsten-Sick** [comment]
https://github.com/evilsocket/bleah/pull/51

Is this what you are looking for ? It logs the data to a JSON file.
