### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by amias-channer** [evilsocket/bleah#16]
there was an error in the setup.py packages line  (line 37) that cause the build command to fail.
with this error 

    TypeError: can only concatenate list (not "str") to list

i fixed it by changing that line to add a package selection  as follows.

    packages=find_packages(where='bleah.*'), 

hope that helps

**Comment by phr0nak** [comment]
@evilsocket New error added after this commit:

<img width="707" alt="screen shot 2017-10-06 at 12 24 10 pm" src="https://user-images.githubusercontent.com/4283403/31273998-53dfb574-aa91-11e7-91ba-c6134e3d3a98.png">

Thanks.

**Comment by evilsocket** [comment]
reverted

**Comment by phr0nak** [comment]
Thanks for the quick fix.
