### ISSUE TITLE
error reading datafile

### ISSUE THREAD

**Issue by NadSo** [evilsocket/bleah#18]
Hello, 
I wanted to read a data file but I got the following error: 
![datafile_error](https://user-images.githubusercontent.com/29726124/31337204-8b71b7c4-acfa-11e7-8646-12bf39df5e39.png)

the file.txt is saved under the same directory where the bleah is

**Comment by evilsocket** [comment]
is file.txt in the folder where you're running the tool from?

**Comment by NadSo** [comment]
file.txt is saved under: Desktop->bleah-master->bleah

**Comment by evilsocket** [comment]
you're running the tool from your home folder, give it the correct path of the file, how do you even expect it to work if you don't do that?! -.-

**Comment by NadSo** [comment]
but that is what I did

**Comment by evilsocket** [comment]
no, your CWD is your home, so `-r file.txt` means `-r /home/kamdem/file.txt` which obviously does not exist .. learn to use a terminal please.

**Comment by NadSo** [comment]
Is it supposed to do that?

![datafile](https://user-images.githubusercontent.com/29726124/31337559-2a8a3236-acfc-11e7-9a3c-a86855f12d8a.png)

**Comment by NadSo** [comment]
I thought it would Read data to be written from the file.txt.

**Comment by evilsocket** [comment]
There's a help menu and several examples in the README, you clearly didn't bother reading and understanding that documentation.

**Comment by NadSo** [comment]
no it is not true. In the README the description says "Read data to be written from this file" . There is not any example about the datafile.

**Comment by yungtravla** [comment]
it can be any data

**Comment by NadSo** [comment]
thanks yungtravla for your reply. But I thought the data in my file.txt should be read

**Comment by yungtravla** [comment]
? The grammar in the --help and README.md are correct, maybe you are misinterpreting?

Bleah reads the data - that will be written - from your text file

**Comment by yungtravla** [comment]
so it reads whatever contents from your file.txt and writes it to the UUID that you specify from a ble device

**Comment by NadSo** [comment]
so for example if my file.txt contents the data: 1,2,3,4. the tool will write this data to the UUID ?

**Comment by yungtravla** [comment]
Have you tried `--data`? Then you will understand `--datafile`/`-r`

**Comment by NadSo** [comment]
yes I did. --data is used to write some data to the characteristic

**Comment by yungtravla** [comment]
and yes.

**Comment by yungtravla** [comment]
bingo, and `--datafile` does the same, but reads the data from a file

**Comment by NadSo** [comment]
In the same way --datafile/r is used the write data to characteristic from the file.txt, right?

**Comment by yungtravla** [comment]
that is exactly what I said and what is written in the docs.

**Comment by yungtravla** [comment]
wait. what...? Did you really just say it is used to write data **to characteristics from the file.txt**? Grammar plz

**Comment by yungtravla** [comment]
please explain to me what characteristics from a txt file are

**Comment by NadSo** [comment]
Thank you so much. So by using --datafile I have to specify which characteristic I want to write data to. That is what was missing

**Comment by NadSo** [comment]
I meant write data from the file to characteristics

**Comment by yungtravla** [comment]
try `bleah -t10 -fe`

**Comment by yungtravla** [comment]
wait 20 seconds, and bleah will enumerate all the characteristics

**Comment by yungtravla** [comment]
`000fe00-000f-00f0-00f0-0000f00f0f0f00f` these address types are UUIDs, you can write data to a UUID if it has the `WRITE` property listed next to it

**Comment by evilsocket** [comment]
Fixed by properly handling the exception:

![lulz](https://user-images.githubusercontent.com/86922/31346756-6eaa32a4-ad1a-11e7-98c5-6c833eec236d.png)
