### ISSUE TITLE
Write binary values to a characteristic

### ISSUE THREAD

**Issue by tautology0** [evilsocket/bleah#22]
At the moment you can only write ASCII data to a characteristic. Many characteristics (e.g. 2a06) take only a binary value. At the moment you have to mangle it into a file.

So, can we have an option to write a hex string (similar to the way gatttool works), e.g. to send \x01\x02\x03

`bleah -i 1 -b aa:bb:cc:dd:ee:ff -u 0123 -x 010203`

Alternatively, allow python style escapes in the string, such as:

`bleah -i 1 -b aa:bb:cc:dd:ee:ff -u 0123 -d '\x01\x02\x03'`

**Comment by evilsocket** [comment]
Mmmm maybe I can just support both:

    --data "somestringhere"

and

    --data 0x12345....
