### ISSUE TITLE
build on raspberry issue

### ISSUE THREAD

**Issue by megahz** [evilsocket/bleah#26]
hi got this when building on rp3:
```
root@osmc:/home/osmc/bleah# python setup.py build
running build
running build_py
running egg_info
writing requirements to bleah.egg-info/requires.txt
writing bleah.egg-info/PKG-INFO
writing top-level names to bleah.egg-info/top_level.txt
writing dependency_links to bleah.egg-info/dependency_links.txt
reading manifest file 'bleah.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '.DS_Store'
warning: no previously-included files found matching '.gitignore'
warning: no files found matching 'distribute_setup.py'
writing manifest file 'bleah.egg-info/SOURCES.txt'
error: can't copy 'bleah/osmc/bleah/bleah/oui.dat': doesn't exist or not a regular file

```
i am using the osmc (media center distribution) but mainly is a raspbian, got many tools running on it.

**Comment by evilsocket** [comment]
well the file is here -> https://github.com/evilsocket/bleah/blob/master/bleah/oui.dat ... it looks like you didn't clone it properly?

**Comment by evilsocket** [comment]
( also lots of ppl installed it on a rpi with no issues, myself included ... )

**Comment by megahz** [comment]
you are right the file was there.

i've notcied though that the error was: mkdir: cannot create directory 'bleah/osmc/bleah/bleah': No such file or directory


so i created that directory bleah/osmc/bleah/bleah and manually copied the oui.dat there and then it build

**Comment by evilsocket** [comment]
which again, it means your folder structure was corrupted for some reason ... glad you solved, closing :+1:
