### ISSUE TITLE
setup.py - error: can't copy

### ISSUE THREAD

**Issue by meoso** [evilsocket/bleah#28]
Commit 926f889 not working for me -- setup not decoding path `./`

`error: can't copy 'bleah/USERNAME/bleah/bleah/oui.dat': doesn't exist or not a regular file`

`Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux`

**Comment by Virgula0** [comment]
same error
