### ISSUE TITLE
Documentation Corrections

### ISSUE THREAD

**Issue by jreynders** [evilsocket/bleah#35]
Bluepy has a prerequisite libglib2.0-dev.  This line is missing in **Install bluepy from source**::
$ sudo apt-get install git build-essential libglib2.0-dev

Alternatively could use the PIP instructions or just reference the BluePy github.

In the **Examples**:
sudo bleah -b "aa:bb:cc:dd:ee:ff" -e
~~Quotes around the MAC does not work, at least on Kali Linux~~
sudo bleah -b aa:bb:cc:dd:ee:ff -e    also works without quotes

**Comment by Wh1t3Fox** [comment]
Tested on Archlinux and Kali and worked with and without quotes

**Comment by jreynders** [comment]
Corrected initial entry - Thanks
