### ISSUE TITLE
local variable 'raw' referenced before assignment

### ISSUE THREAD

**Issue by 9andrea1** [evilsocket/bleah#54]
hi, 
i get the error in title when enumerating device. moreover, if i try to write i get the same error on a function call.

i fixed it as follows:

in scan.py: 
added from bleah.write import *

in enumerate.py (function enumerate_device_properties):
added raw=None initialization

**Comment by t4canty** [comment]
Hi 9andrea1
Where did you initialize raw = None

**Comment by 9andrea1** [comment]
hi,
line 449 (inside the chars cycle)

**Comment by t4canty** [comment]
> hi,
> line 449 (inside the chars cycle)

9andrea1

Thanks for the fix, works perfectly

**Comment by To3t** [comment]
Now i might be missing a busload here, but line 449 does not do it for me where do i state raw = None
 #  chars = s.getCharacteristics()
        for char in chars:
	raw = None 
            props = char.propertiesToString()
	   
            if 'READ' in props and 'INDICATE' not in props:
                try:
                    raw = char.read()
                except:
                    raw = None
