### ISSUE TITLE
Error after running bleah

### ISSUE THREAD

**Issue by Michiel4211** [evilsocket/bleah#8]
After running, "sudo bleah" in the terminal the following error will appear :

Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 4, in <module>
    __import__('pkg_resources').run_script('bleah==1.0.0', 'bleah')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1505, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 118, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 78, in main
    devices = start_scan(args)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 162, in start_scan
    return scanner.scan(args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 679, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 617, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 276, in _mgmtCmd
    "Failed to execute mgmt cmd '%s'" % (cmd))
bluepy.btle.BTLEException: Failed to execute mgmt cmd 'le on'

I would like help for solving this :D
OS : Kali Linux 2016.2

**Comment by evilsocket** [comment]
To solve this, use the instructions provided in the README, you didn't install bluepy as mentioned there.

**Comment by Michiel4211** [comment]
I did install it exactly as mentioned, followed every step. Or do you need to git clone and install bleah inside bluepy folder?

**Comment by Michiel4211** [comment]
After running the install of bluepy setup.py it gave the following error :

running install
Working dir is /root/bluepy
execute make -C ./bluepy clean
execute make -C bluepy -j1
Failed to compile bluepy-helper. Exiting install.
Command was 'make -C bluepy -j1' in /root/bluepy
Return code was 2
Output was:
make: Entering directory '/root/bluepy/bluepy'
tar xzf bluez-src.tgz
touch ./bluez-5.29/lib/bluetooth.c ./bluez-5.29/lib/hci.c ./bluez-5.29/lib/sdp.c ./bluez-5.29/lib/uuid.c ./bluez-5.29/attrib/att.c ./bluez-5.29/attrib/gatt.c ./bluez-5.29/attrib/gattrib.c ./bluez-5.29/attrib/utils.c ./bluez-5.29/btio/btio.c ./bluez-5.29/src/log.c ./bluez-5.29/src/shared/mgmt.c ./bluez-5.29/src/shared/crypto.c ./bluez-5.29/src/shared/att.c ./bluez-5.29/src/shared/queue.c ./bluez-5.29/src/shared/util.c ./bluez-5.29/src/shared/io-glib.c ./bluez-5.29/src/shared/timeout-glib.c
make: pkg-config: Command not found
make: pkg-config: Command not found
gcc -L. -Os -g -Wall  -DHAVE_CONFIG_H -I./bluez-5.29/attrib -I./bluez-5.29 -I./bluez-5.29/lib -I./bluez-5.29/src -I./bluez-5.29/gdbus -I./bluez-5.29/btio  -o bluepy-helper bluepy-helper.c ./bluez-5.29/lib/bluetooth.c ./bluez-5.29/lib/hci.c ./bluez-5.29/lib/sdp.c ./bluez-5.29/lib/uuid.c ./bluez-5.29/attrib/att.c ./bluez-5.29/attrib/gatt.c ./bluez-5.29/attrib/gattrib.c ./bluez-5.29/attrib/utils.c ./bluez-5.29/btio/btio.c ./bluez-5.29/src/log.c ./bluez-5.29/src/shared/mgmt.c ./bluez-5.29/src/shared/crypto.c ./bluez-5.29/src/shared/att.c ./bluez-5.29/src/shared/queue.c ./bluez-5.29/src/shared/util.c ./bluez-5.29/src/shared/io-glib.c ./bluez-5.29/src/shared/timeout-glib.c 
bluepy-helper.c:33:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/attrib/att.c:33:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/attrib/gatt.c:32:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/attrib/gattrib.c:34:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/attrib/utils.c:30:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/btio/btio.c:37:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/src/log.c:32:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/src/shared/io-glib.c:30:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
./bluez-5.29/src/shared/timeout-glib.c:22:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
Makefile:28: recipe for target 'bluepy-helper' failed
make: *** [bluepy-helper] Error 1
make: Leaving directory '/root/bluepy/bluepy'

I fixed this by "sudo apt-get install git build-essential libglib2.0-dev" but then it still wouldn't run.
